// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalypipl6VRwFDmSBej817e27WShBLMiM',
    appId: '1:226367086845:web:a28554688c9edb4c625e94',
    messagingSenderId: '226367086845',
    projectId: 'toramproject-212ee',
    authDomain: 'toramproject-212ee.firebaseapp.com',
    storageBucket: 'toramproject-212ee.firebasestorage.app',
    measurementId: 'G-PHN6G137Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxEyOuizY6t4ZuOapGoY0QJUO9ZEwaee4',
    appId: '1:226367086845:android:46a87382d9f0acc0625e94',
    messagingSenderId: '226367086845',
    projectId: 'toramproject-212ee',
    storageBucket: 'toramproject-212ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv0cdoWY5OCiiPUebtpN9BGd9Pa232ySA',
    appId: '1:226367086845:ios:cdb80ef0b68cfd9c625e94',
    messagingSenderId: '226367086845',
    projectId: 'toramproject-212ee',
    storageBucket: 'toramproject-212ee.firebasestorage.app',
    iosClientId: '226367086845-adgsk9uf5rj0nt22mudvuc5qtml2efr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.toramonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv0cdoWY5OCiiPUebtpN9BGd9Pa232ySA',
    appId: '1:226367086845:ios:cdb80ef0b68cfd9c625e94',
    messagingSenderId: '226367086845',
    projectId: 'toramproject-212ee',
    storageBucket: 'toramproject-212ee.firebasestorage.app',
    iosClientId: '226367086845-adgsk9uf5rj0nt22mudvuc5qtml2efr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.toramonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBalypipl6VRwFDmSBej817e27WShBLMiM',
    appId: '1:226367086845:web:9363f23ee1f09f01625e94',
    messagingSenderId: '226367086845',
    projectId: 'toramproject-212ee',
    authDomain: 'toramproject-212ee.firebaseapp.com',
    storageBucket: 'toramproject-212ee.firebasestorage.app',
    measurementId: 'G-TTZF2K0X9L',
  );

}